{% set name = "torchvista" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchvista-{{ version }}.tar.gz
  sha256: ae410dd4288eca2f6e911065837963a1e1ad56d96fb314a5cb8b4e79e9a5962e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ipython >=7.0.0
    - numpy >=1.18.0
    - pytorch

test:
  imports:
    - torchvista
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sachinhosmani/torchvista
  summary: Interactive PyTorch model visualizer for notebooks
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - NOTICE.txt

extra:
  recipe-maintainers:
    - sachinhosmani
